# Generated by Django 4.1.7 on 2023-03-25 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(blank=True, max_length=500, null=True)),
                ('category_slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_date', models.DateTimeField(auto_now_add=True)),
                ('topic_slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
                ('topic_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.category')),
                ('topic_opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_content', models.TextField(max_length=500)),
                ('post_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.topic')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
