# Generated by Django 4.1.7 on 2023-03-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_topic_topic_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_uuid',
        ),
    ]
